### ISSUE TITLE
It takes a really long time to clone this repo because of its size.

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno_third_party#61]
This repo has estimated size of 277.52MB, 21 times bigger that main deno repo (12.88MB). It is a huge pain to clone.

![screenshot](https://user-images.githubusercontent.com/11488886/78418226-83e74380-7664-11ea-8473-f830b1ba5bf9.png)

## Proposal

Use package managers, most of my packages are cached, so the time it takes to download and install them would be reduced significantly.

**Comment by hayd** [comment]
Use --depth=50 or some other small number. Then clone will be much faster/what you download smaller.

**Comment by KSXGitHub** [comment]
According to the [manua](https://deno.land/std/manual.md#cloning-the-repository), how do I do `git clone --recurse-submodules https://github.com/denoland/deno.git` with `--depth` for submodules?

**Comment by hayd** [comment]
Ah, you need --shallow-submodules (and a recent git):

```
git clone --depth=1 --shallow-submodules --recurse-submodules https://github.com/denoland/deno.git
```

took 40s on my machine.

**Comment by KSXGitHub** [comment]
> Ah, you need --shallow-submodules (and a recent git):
> 
> ```
> git clone --depth=1 --shallow-submodules --recurse-submodules https://github.com/denoland
> ```

You should add this to [manual.md](https://deno.land/std/manual.md#cloning-the-repository) for future contributors.
